### ISSUE TITLE
R24BBD1

### ISSUE THREAD

**Issue by zenbooster** [marcnewlin/human-detector-detector#1]
Hello! Will this firmware work with the R24BBD1 module?

**Comment by zenbooster** [comment]
It doesn't seem to work...

```
user@ub64devel:~/git/human-detector-detector$ make reset && sleep 1 && ./stream-iq.py
cd openocd/tcl && ./openocd -f interface/jlink.cfg \
  	         -c "transport select swd" \
  					 -f target/stm32f1x.cfg \
  					 -c "init" \
  					 -c "reset run" \
 						 -c "exit"
Open On-Chip Debugger 0.11.0+dev-00656-g66335683f-dirty (2023-02-14-17:58)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
swd
Info : DEPRECATED target event trace-config; use TPIU events {pre,post}-{enable,disable}
Info : J-Link OB-STM32F072-CortexM compiled Jan  7 2019 14:09:37
Info : Hardware version: 1.00
Info : VTarget = 3.300 V
Info : clock speed 1000 kHz
Info : SWD DPIDR 0x2ba01477
Info : [stm32f1x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f1x.cpu] target has 6 breakpoints, 4 watchpoints
Info : [stm32f1x.cpu] external reset detected
Info : starting gdb server for stm32f1x.cpu on 3333
Info : Listening on port 3333 for gdb connections
response=b''
Traceback (most recent call last):
  File "/home/user/git/human-detector-detector/./stream-iq.py", line 110, in <module>
    c.configure_gpio(GPIOA, 6, GPIO_ANALOG)
  File "/home/user/git/human-detector-detector/./stream-iq.py", line 102, in configure_gpio
    cmd_code, status = struct.unpack("II", response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes

```

**Comment by zenbooster** [comment]
Oops, it works!!! For the first time I tried to connect through UART. In the second, via USB, but it was necessary to connect D+ D- to the lower pins of the group.
![ub64devel-2023-02-15-18-22-57](https://user-images.githubusercontent.com/49373256/219073043-f811508b-720f-4961-a462-59355dd5f68d.png)

**Comment by zenbooster** [comment]
And in my case, the delay should be not one, but two seconds:
`make reset && sleep 2 && ./stream-iq.py | baudline -stdin -channels 2 -quadrature -record -fftsize 2048 -flipcomplex`

**Comment by zenbooster** [comment]
I suggest adding to the description that this module is also supported.
